 version: 2
 jobs:
   build:
     working_directory: ~/gisida
     docker:
       - image: circleci/node:6.10.3
     steps:
       - checkout
       - run: 
           name: Install Dependencies
           command: yarn install
       - run: 
           name: Run ESLint
           command: npm run lint
